global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'motif-system'
    replica: 'prometheus-1'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Motif API application metrics
  - job_name: 'motif-api'
    static_configs:
      - targets: ['motif_api:8000']
    metrics_path: /motif/metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: motif_api:8000

  # PostgreSQL database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: postgresql

  # Redis cache metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: redis

  # Nginx reverse proxy metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /metrics
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: nginx

  # Node exporter for system metrics (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: node

  # Docker container metrics (if using cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: cadvisor

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Additional configuration
remote_write:
  # Add remote write configuration if using external storage
  # - url: "https://your-remote-storage/api/v1/write"
  #   basic_auth:
  #     username: "your-username"
  #     password: "your-password"

remote_read:
  # Add remote read configuration if using external storage
  # - url: "https://your-remote-storage/api/v1/read"
  #   basic_auth:
  #     username: "your-username" 
  #     password: "your-password" 