apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: visual-dm-backend-pvc
  labels:
    app: visual-dm-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""  # Use default storage class 