apiVersion: batch/v1
kind: CronJob
metadata:
  name: visualdm-backup
spec:
  schedule: "0 2 * * *"  # Run at 2 AM every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:14-alpine
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -h $DB_HOST -U $DB_USER -d $DB_NAME | gzip > /backups/visualdm-$(date +%Y%m%d).sql.gz
              aws s3 cp /backups/visualdm-$(date +%Y%m%d).sql.gz s3://$S3_BUCKET/backups/
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: visualdm-backup-secrets
                  key: db-host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: visualdm-backup-secrets
                  key: db-user
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: visualdm-backup-secrets
                  key: db-name
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: visualdm-backup-secrets
                  key: db-password
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: visualdm-backup-secrets
                  key: s3-bucket
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: visualdm-backup-secrets
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: visualdm-backup-secrets
                  key: aws-secret-key
            volumeMounts:
            - name: backup-volume
              mountPath: /backups
          volumes:
          - name: backup-volume
            emptyDir: {}
          restartPolicy: OnFailure 