apiVersion: batch/v1
kind: Job
metadata:
  name: pg-restore
  namespace: visualdm
spec:
  template:
    spec:
      containers:
        - name: pg-restore
          image: postgres:15
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: visualdm-secrets
                  key: POSTGRES_PASSWORD
          command: ["/bin/sh", "-c"]
          args:
            - "psql -h db -U postgres -d visualdm < /backup/visualdm-$(date +%F).sql"
          volumeMounts:
            - name: backup
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: pg-backup-data 