apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-storage 