apiVersion: v1
kind: Secret
metadata:
  name: visualdm-secrets
  namespace: visualdm
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  JWT_SECRET_KEY: your-jwt-secret

# For production, use:
# kubectl create secret generic visualdm-secrets \
#   --from-literal=database-url=... \
#   --from-literal=redis-url=... \
#   --from-literal=jwt-secret=... 