apiVersion: v1
kind: Secret
metadata:
  name: visual-dm-secrets
  namespace: visual-dm
type: Opaque
stringData:
  postgres-user: "your-postgres-user"
  postgres-password: "your-postgres-password"
  postgres-db: "your-postgres-db"
  redis-password: "your-redis-password" 