export enum ErrorCategory {
    INVALID_TARGET = 'INVALID_TARGET',
    INSUFFICIENT_RESOURCES = 'INSUFFICIENT_RESOURCES',
    COOLDOWN_ACTIVE = 'COOLDOWN_ACTIVE',
    STATE_CONFLICT = 'STATE_CONFLICT',
    PERMISSION_DENIED = 'PERMISSION_DENIED',
    OUT_OF_RANGE = 'OUT_OF_RANGE',
    INVALID_ACTION = 'INVALID_ACTION',
    UNKNOWN = 'UNKNOWN',
} 