"""Add cleanup tables

Revision ID: 797e78e0b2d8
Revises: 001
Create Date: 2025-05-02 17:28:34.889755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '797e78e0b2d8'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_alerts', 'alert_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_budget_alerts_alert_time', table_name='budget_alerts')
    op.alter_column('budgets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_budgets_scope_id', table_name='budgets')
    op.drop_index('ix_budgets_scope_type', table_name='budgets')
    op.alter_column('cleanup_entries', 'identified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_cleanup_entries_identified_at', table_name='cleanup_entries')
    op.drop_index('ix_cleanup_entries_status', table_name='cleanup_entries')
    op.alter_column('cloud_providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('cloud_providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cloud_providers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cloud_resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cloud_resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_cloud_resources_resource_id', table_name='cloud_resources')
    op.drop_index('ix_cloud_resources_resource_type', table_name='cloud_resources')
    op.alter_column('cost_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_cost_entries_end_time', table_name='cost_entries')
    op.drop_index('ix_cost_entries_service_name', table_name='cost_entries')
    op.drop_index('ix_cost_entries_start_time', table_name='cost_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cost_entries_start_time', 'cost_entries', ['start_time'], unique=False)
    op.create_index('ix_cost_entries_service_name', 'cost_entries', ['service_name'], unique=False)
    op.create_index('ix_cost_entries_end_time', 'cost_entries', ['end_time'], unique=False)
    op.alter_column('cost_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_cloud_resources_resource_type', 'cloud_resources', ['resource_type'], unique=False)
    op.create_index('ix_cloud_resources_resource_id', 'cloud_resources', ['resource_id'], unique=False)
    op.alter_column('cloud_resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cloud_resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cloud_providers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cloud_providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cloud_providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('ix_cleanup_entries_status', 'cleanup_entries', ['status'], unique=False)
    op.create_index('ix_cleanup_entries_identified_at', 'cleanup_entries', ['identified_at'], unique=False)
    op.alter_column('cleanup_entries', 'identified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_budgets_scope_type', 'budgets', ['scope_type'], unique=False)
    op.create_index('ix_budgets_scope_id', 'budgets', ['scope_id'], unique=False)
    op.alter_column('budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('ix_budget_alerts_alert_time', 'budget_alerts', ['alert_time'], unique=False)
    op.alter_column('budget_alerts', 'alert_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ### 