openapi: 3.0.3
info:
  title: Visual DM Search API
  version: 1.0.0
  description: API documentation for search and filtering endpoints.
paths:
  /api/search/worlds:
    get:
      summary: Search Worlds
      description: Search for worlds with filtering, sorting, and pagination.
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search term
        - in: query
          name: filter
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
          description: Filter fields, e.g. filter[name]=Earth
        - in: query
          name: sort
          schema:
            type: string
          description: Sort field and direction, e.g. name:asc
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Results per page
      responses:
        '200':
          description: Successful search response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
components:
  schemas:
    SearchResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
        total:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer 